### ISSUE TITLE
在DBLP数据集下报错

### ISSUE THREAD

**Issue by zbw0329** [wangtong627/DCAGC#1]
您好，感谢您出色的工作
我在使用这份代码的时候，将参数中的数据集改成DBLP，报错如下
貌似是网络生成的矩阵相乘尺寸不正确，请问如何调整？
![1660800384023](https://user-images.githubusercontent.com/50667397/185300780-6443e527-50d0-487f-bec8-90f4d5d27adf.png)

**Comment by wangtong627** [comment]
您好
自表达矩阵C的维度是N*N(样本数)。
这里2708是默认Cora数据集的样本数，与DBLP不符，应修改为DBLP数据集的样本数17716。我们当时因为设备有限，没有跑DBLP这个数据集。
有一个参数设置的json文件，可以修改维度N的数值。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangtong627/NCAGC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月18日(星期四) 中午1:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wangtong627/NCAGC] 在DBLP数据集下报错 (Issue #1)





 
您好，感谢您出色的工作
 我在使用这份代码的时候，将参数中的数据集改成DBLP，报错如下
 貌似是网络生成的矩阵相乘尺寸不正确，请问如何调整？

**Comment by zbw0329** [comment]
感谢您的回复

**Comment by zbw0329** [comment]
您好，我查询资料发现DBLP数据集的样本数目是4057，Cora数据集的数目为2708
这里为何是现实17716，是4057*4
我使用的是单张的1080Ti，显存11G，用别的算法跑DBLP都不会爆显存，但是NCAGC在DBLP会爆显存，现在没有什么头绪，请问能否指点一下？

**Comment by zbw0329** [comment]
您好，我能够复现了论文中Cora以及citeseer数据集
但是ACM没有对应的JSON文件，不知道是否可以提供？
WIKICS的JSON文件无法正确的运行

**Comment by zbw0329** [comment]
![1661500639936](https://user-images.githubusercontent.com/50667397/186852626-f8bd2452-e2c3-4438-8fea-01af12cf9a3e.png)
****
还有我想请问一下这个CiteSeer的Encoder的输入维度应该是数据集的特征维度3703吧？而不是数据集的样本个数？不知道我的理解是否有误，我看见表格中其他数据集的encoder输入维度都是特征维度

**Comment by wangtong627** [comment]
这是PyTorch Geometric 的DBLP-Full。如果要跑4057的DBLP可以自行更换数据集



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangtong627/NCAGC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月26日(星期五) 中午1:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangtong627/NCAGC] 在DBLP数据集下报错 (Issue #1)





 
您好，我查询资料发现DBLP数据集的样本数目是4057，Cora数据集的数目为2708
 这里为何是现实17716，是4057*4
 我使用的是单张的1080Ti，显存11G，用别的算法跑DBLP都不会爆显存，但是NCAGC在DBLP会爆显存，现在没有什么头绪，请问能否指点一下？

**Comment by wangtong627** [comment]
这里是输入样本的特征维度，应该是3703

**Comment by wangtong627** [comment]
> ![1661500639936](https://user-images.githubusercontent.com/50667397/186852626-f8bd2452-e2c3-4438-8fea-01af12cf9a3e.png)
> 
> 还有我想请问一下这个CiteSeer的Encoder的输入维度应该是数据集的特征维度3703吧？而不是数据集的样本个数？不知道我的理解是否有误，我看见表格中其他数据集的encoder输入维度都是特征维度

这里是输入样本的特征维度，应该是3703

**Comment by zbw0329** [comment]
谢谢您的回复。
我看见自表示模块在代码中都注释掉了，请问是否最后没有使用自表示模块？
![1661561776569](https://user-images.githubusercontent.com/50667397/187007947-ae163063-dbe9-4d67-962d-07738e458667.png)

**Comment by wangtong627** [comment]
自表达这部分直接写在Model里了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangtong627/NCAGC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月27日(星期六) 上午8:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangtong627/NCAGC] 在DBLP数据集下报错 (Issue #1)





 
谢谢您的回复。
 我看见自表示模块在代码中都注释掉了，请问是否最后没有使用自表示模块？

**Comment by zbw0329** [comment]
感谢您的帮助

**Comment by wangtong627** [comment]
是的，这边是样本的X维度。可能写错了




TongWang(王通）
***@***.***

South&nbsp;East&nbsp;University&nbsp;(东南大学)


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangtong627/NCAGC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月26日(星期五) 下午3:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangtong627/NCAGC] 在DBLP数据集下报错 (Issue #1)





 

 
 
还有我想请问一下这个CiteSeer的Encoder的输入维度应该是数据集的特征维度3703吧？而不是数据集的样本个数？不知道我的理解是否有误，我看见表格中其他数据集的encoder输入维度都是特征维度
